### ISSUE TITLE
--hostでエラー発生

### ISSUE THREAD

**Issue by smdhnz** [qrac/minista#35]
yarn devで--hostオプション付けたところエラー出ました。バグですか？仕様ですか？

環境
wsl2 ubuntu20.04

```bash
$ npm init minista@latest new -- --template ts
Need to install the following packages:
  create-minista@latest
Ok to proceed? (y) y

create-minista (v2.0.0)
✔ Project name (in the file): … new
> Copying project files...
✔ Done!

Next steps:
  1: cd new
  2: npm install (or pnpm install, yarn, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional step)
  4: npm run dev (or pnpm, yarn, etc)

To close the dev server, hit Ctrl-C
$ cd new/
$ yarn
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "minista > @mdx-js/rollup@2.1.1" has unmet peer dependency "rollup@>=2".
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.18", while you're on "1.22.17".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
Done in 19.52s.
$ yarn dev
yarn run v1.22.17
$ minista
  > Local: http://localhost:3000/
  > Network: use `--host` to expose
$ yarn dev --host
yarn run v1.22.17
$ minista --host
file:///home/ubuntu/projects/cc/new/node_modules/cac/dist/index.mjs:400
          throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
                ^

CACError: Unknown option `--host`

    at Command.checkUnknownOptions (file:///home/ubuntu/projects/cc/new/node_modules/cac/dist/index.mjs:400:17)
    at CAC.runMatchedCommand (file:///home/ubuntu/projects/cc/new/node_modules/cac/dist/index.mjs:598:13)
    at CAC.parse (file:///home/ubuntu/projects/cc/new/node_modules/cac/dist/index.mjs:537:12)
    at file:///home/ubuntu/projects/cc/new/node_modules/minista/dist/cli.js:93:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by qrac** [comment]
ご報告ありがとうございます。devサーバーのオプションはまだ作っていないのでv2.1.0時点では仕様となります。

**Comment by qrac** [comment]
CLI側は作っていませんが、コンフィグファイルでの指定はできますので `minista.config.js` をルートに置いてViteの設定を書き込むとv2.1.0でも同様のことができます。

```js
import { defineConfig } from "minista"

export default defineConfig({
  vite: {
    server: {
      host: true,
    },
  },
})
```

**Comment by smdhnz** [comment]
ご確認ありがとうございます。
承知いたしました。

**Comment by qrac** [comment]
@smdhnz 
v2.3.0にてCLIオプションを作成しました！
https://minista.qranoko.jp/docs/commands#option

**Comment by smdhnz** [comment]
ご対応ありがとうございます！
